# tasks file for setup role

- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install dependencies
  become: yes
  apt:
    name:
      - nodejs
      - npm

- name: Install pm2
  become: yes
  npm:
    name: pm2
    global: yes

- name: Create ~/web directory
  become: yes
  file:
    path: ~/web
    state: directory

- name: Copy index.js file to ~/web directory
  become: yes
  copy:
    src: files/index.js
    dest: ~/web/index.js

- name: Start web server with pm2
  become: yes
  command: pm2 start ~/web/index.js -f